const { withAppBuildGradle, withGradleProperties } = require('expo/config-plugins');

// The Expo template's 2 GB heap / 512 MB metaspace is too small for this project's release build:
// `lintVitalAnalyzeRelease` across every native module fails with OutOfMemoryError: Metaspace.
const JVM_ARGS = '-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8';

// The app module compiles every autolinked library's codegen, and on Windows those object paths
// pass 260 characters. The default CMake 3.22.1 ships ninja 1.10, which cannot open them
// ("Filename longer than 260 characters"); CMake 3.31.6 ships ninja 1.12, which can.
const CMAKE_VERSION = '3.31.6';
const CMAKE_START = '// @generated by TillExpiry: app CMake version';
const CMAKE_END = '// @end generated TillExpiry app CMake version';

const withJvmArgs = config => withGradleProperties(config, cfg => {
  const existing = cfg.modResults.find(p => p.type === 'property' && p.key === 'org.gradle.jvmargs');
  if (existing) existing.value = JVM_ARGS;
  else cfg.modResults.push({ type: 'property', key: 'org.gradle.jvmargs', value: JVM_ARGS });
  return cfg;
});

const withAppCmakeVersion = config => withAppBuildGradle(config, cfg => {
  if (cfg.modResults.language !== 'groovy') {
    throw new Error('[TillExpiry] App CMake version requires a Groovy app build file.');
  }
  const blockPattern = new RegExp(`\\n*${CMAKE_START}[\\s\\S]*?${CMAKE_END}`, 'g');
  const contents = cfg.modResults.contents.replace(blockPattern, '').trimEnd();
  cfg.modResults.contents = `${contents}\n\n${CMAKE_START}
android {
    externalNativeBuild {
        cmake {
            version "${CMAKE_VERSION}"
        }
    }
}
${CMAKE_END}\n`;
  return cfg;
});

module.exports = config => withAppCmakeVersion(withJvmArgs(config));
