#!/usr/bin/env node
// Regenerate docs/REUSE_PROVENANCE.md by comparing every source file with the pinned reference repos.
// Usage: TILLCALC_DIR=../Tillcalc TILLNOTE_DIR=../PrivateBusinessVault_Master_v10_2 TILLLABEL_DIR=../Till-lable node scripts/genProvenance.mjs
// Source repos are read with `git show <sha>:<path>`; they are never modified.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const TC = { name: 'TillCalc', dir: process.env.TILLCALC_DIR || '../Tillcalc', sha: 'e7ea8caadd1b2f2e663b3c8059b4102d5515adcc' };
const TN = { name: 'Till Note', dir: process.env.TILLNOTE_DIR || '../PrivateBusinessVault_Master_v10_2', sha: '6fa6e941ac7e94334519c435f8bae3bf9d160826' };
const TL = { name: 'TillLabel', dir: process.env.TILLLABEL_DIR || '../Till-lable', sha: '8f31e88' };
const notes = JSON.parse(fs.readFileSync(path.join('scripts', 'provenance-notes.json'), 'utf8'));

const show = (repo, file) => { try { return execFileSync('git', ['-C', repo.dir, 'show', `${repo.sha}:${file}`], { stdio: ['ignore', 'pipe', 'ignore'], maxBuffer: 64 << 20 }); } catch { return null; } };
const files = execFileSync('git', ['ls-files', 'src', 'scripts', '__mocks__', 'plugins', 'android-libs', 'app.json', 'package.json', 'eas.json', '.github'], { encoding: 'utf8' }).split('\n').filter(f => f && !/\/locales\/|__tests__/.test(f));

const rows = [];
for (const f of files) {
  const local = fs.readFileSync(f);
  let row = null;
  for (const repo of [TC, TL]) {
    const src = show(repo, f);
    if (!src) continue;
    const same = Buffer.compare(src, local) === 0;
    row = { f, app: repo.name, src: f, sha: repo.sha.slice(0, 8), how: same ? 'copied' : 'adapted' };
    break;
  }
  const note = notes[f];
  if (note?.source) row = { f, app: note.source.app, src: note.source.path, sha: note.source.sha, how: note.source.how };
  if (!row) row = { f, app: '—', src: '—', sha: '—', how: 'new' };
  row.reason = note?.reason ?? (row.how === 'copied' ? 'Family shell, unchanged' : row.how === 'new' ? 'TillExpiry domain' : 'Family shell, TillExpiry identity / scope');
  row.changes = note?.changes ?? (row.how === 'copied' ? '—' : row.how === 'new' ? '—' : 'Renamed identifiers, storage namespaces or strings for TillExpiry');
  rows.push(row);
}
const count = h => rows.filter(r => r.how === h).length;
const out = [
  '# Reuse provenance',
  '',
  `Generated by \`node scripts/genProvenance.mjs\` from the working tree. References: TillCalc \`${TC.sha}\` (primary), Till Note \`${TN.sha}\` (secondary, patterns only), TillLabel \`${TL.sha}\` (TillCalc-derived family sibling whose TillCalc copies are traced back to TillCalc where identical).`,
  '',
  `Totals: copied ${count('copied')} · adapted ${count('adapted')} · reimplemented ${count('reimplemented')} · new ${count('new')}. The reference repositories were read with \`git show\` only and were not modified.`,
  '',
  '| TillExpiry file | Source app | Source path | Source SHA | How | Reason | Important changes |',
  '|---|---|---|---|---|---|---|',
  ...rows.map(r => `| \`${r.f}\` | ${r.app} | ${r.src === '—' ? '—' : `\`${r.src}\``} | ${r.sha === '—' ? '—' : `\`${r.sha}\``} | ${r.how} | ${r.reason} | ${r.changes} |`),
  '',
];
fs.writeFileSync('docs/REUSE_PROVENANCE.md', out.join('\n'));
console.log(`provenance: ${rows.length} files`);
